#if defined _INC_y_serverincs
	#endinput
#endif

#define _INC_y_serverincs

// YSI_Coding:

#tryinclude <YSI_Coding\y_async>
#tryinclude <YSI_Coding\y_functional>
#tryinclude <YSI_Coding\y_hooks>
#tryinclude <YSI_Coding\y_inline>
#tryinclude <YSI_Coding\y_malloc>
#tryinclude <YSI_Coding\y_remote>
#tryinclude <YSI_Coding\y_stringhash>
#tryinclude <YSI_Coding\y_timers>
#tryinclude <YSI_Coding\y_unique>
#tryinclude <YSI_Coding\y_va>

// YSI_Core includes:

#tryinclude <YSI_Core\y_als>
#tryinclude <YSI_Core\y_cell>
#tryinclude <YSI_Core\y_compilerdata>
#tryinclude <YSI_Core\y_debug>
#tryinclude <YSI_Core\y_functional>
#tryinclude <YSI_Core\y_master>
#tryinclude <YSI_Core\y_profiling>
#tryinclude <YSI_Core\y_testing>
#tryinclude <YSI_Core\y_utils>

// YSI_Data includes:

#tryinclude <YSI_Data\y_bintree>
#tryinclude <YSI_Data\y_bit>
#tryinclude <YSI_Data\y_circular>
#tryinclude <YSI_Data\y_foreach>
#tryinclude <YSI_Data\y_hashmap>
#tryinclude <YSI_Data\y_jaggedarray>
#tryinclude <YSI_Data\y_playerarray>
#tryinclude <YSI_Data\y_playerset>
#tryinclude <YSI_Data\y_sortedarray>
#tryinclude <YSI_Data\y_sparsearray>

// YSI_Extra includes:

#tryinclude <YSI_Extra\y_extra>
#tryinclude <YSI_Extra\y_files>
#tryinclude <YSI_Extra\y_streamer_plugin>
#tryinclude <YSI_Extra\y_tho>

// YSI_Game includes:

#tryinclude <YSI_Game\y_vehicledata>

// YSI_Players includes:

#tryinclude <YSI_Players\y_groups>
#tryinclude <YSI_Players\y_languages>
#tryinclude <YSI_Players\y_text>
#tryinclude <YSI_Players\y_users

// YSI_Server includes:

#tryinclude <YSI_Server\y_colours>
#tryinclude <YSI_Server\y_colors>
#tryinclude <YSI_Server\y_flooding>
#tryinclude <YSI_Server\y_lock>
#tryinclude <YSI_Server\y_punycode>
#tryinclude <YSI_Server\y_scriptinit>
#tryinclude <YSI_Server\y_stringise>
#tryinclude <YSI_Server\y_stringize>
#tryinclude <YSI_Server\y_td>

// YSI_Storage includes:

#tryinclude <YSI_Storage\y_amx>
#tryinclude <YSI_Storage\y_ini>
#tryinclude <YSI_Storage\y_bitmap>
#tryinclude <YSI_Storage\y_php>
#tryinclude <YSI_Storage\y_svar>
#tryinclude <YSI_Storage\y_uvar>
#tryinclude <YSI_Storage\y_xml>

// YSI_Visual includes:

#tryinclude <YSI_Visual\y_areas>
#tryinclude <YSI_Visual\y_classes>
#tryinclude <YSI_Visual\y_commands>
#tryinclude <YSI_Visual\y_dialog>
#tryinclude <YSI_Visual\y_loader>
#tryinclude <YSI_Visual\y_properties>
#tryinclude <YSI_Visual\y_races>
#tryinclude <YSI_Visual\y_zonenames>
#tryinclude <YSI_Visual\y_zonepulse>